#!/bin/bash

echo "📂 Updating submodules after commit..."
git submodule foreach --recursive --quiet '
  echo "📦 Committing changes in $name...";
  git add . && git commit -m "Update submodule $name" || echo "No changes to commit in $name.";
  echo "✅ Changes in $name committed!";
'
echo "✅ All submodules updated!"
