#!/bin/bash

commit_message=$(git log -1 --pretty=%B)
parent_repo_path=$(git rev-parse --show-superproject-working-tree)

if [ -z "$parent_repo_path" ]; then
	echo "✅ At the root of the repository, finishing up!"
  	exit 0
fi

echo "🚀 Updating parent repository"

submodule_name=$(basename `git rev-parse --show-toplevel`)
submodule_absolute_path=$(git rev-parse --show-toplevel)
submodule_path=$(python3 -c "import os; print(os.path.relpath('$submodule_absolute_path', '$parent_repo_path'))")

cd $parent_repo_path

cleaned_commit_message=$(echo "$commit_message" | sed 's/^auto([^)]*): //')
new_commit_message="auto($submodule_name): $cleaned_commit_message"

git add $submodule_path
git commit -m "$new_commit_message"

echo "✅ All submodules updated!"
