#!/bin/bash

git submodule foreach --recursive --quiet '
    echo "⏳ Pushing $name...";
    branch=$(git rev-parse --abbrev-ref HEAD);
    git push origin $branch --quiet || echo "⭕️ Failed to push $name.";
'
